export { default as Welcome } from './Welcome/Welcome'
export { default as SignIn } from './Welcome/SignIn'
export { default as SignUp } from './Welcome/SignUp'
export { default as Auth2 } from './Welcome/Auth2'
export { default as Dashboard } from './Dashboard/Dashboard'