{
 "title": "Blackbox exporter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Probe success",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "probe_success", "legendFormat": "__auto" }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Probe http status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    { "expr": "probe_http_status_code", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Probe http ssl",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    { "expr": "probe_http_ssl", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Probe http duration (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
   "targets": [
    { "expr": "probe_http_duration_seconds", "legendFormat": "__auto" }
   ]
  }
 ]
}