{
 "title": "Prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Prometheus number of scrapes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_target_scrape_pools_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus scrape time interval",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "prometheus_target_interval_length_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TSDB memory charge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prometheus_tsdb_head_series", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "TSDB storage blocks bytes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_storage_blocks_bytes",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}