export { default as Welcome } from './Welcome/Welcome'
export { default as SignIn } from './Welcome/SignIn'
export { default as SignUp } from './Welcome/SignUp'
export { default as Auth2 } from './Welcome/Auth2'
export { default as Dashboard } from './Dashboard/Dashboard'
export { default as Activity } from './Dashboard/Activity/Activity'
export { default as Achievement } from './Dashboard/Achievement/Achievement'
export { default as Conversations } from './Dashboard/Conversations/Conversations'
export { default as Ressources } from './Dashboard/Ressources/Ressources'
export { default as ExportData } from './Dashboard/ExportData/ExportData'
export { default as About } from './Dashboard/About/About'
export { default as Profile } from './Dashboard/Profile/Profile'
export { default as Settings } from './Dashboard/Settings/Settings'

